### ISSUE TITLE
Blood Aura and Blood Flask are broken

### ISSUE THREAD

**Issue by Sazuzaki** [cojalexandru/sanguine_arsenal#2]
Heyo, Blood Aura and the Blood Flask don't work properly in the latest version

- Blood Aura does not grant the bonus multiplier it should when activated. Turning it on does nothing but drain your blood, and ultimately just exists for you to shoot yourself in the foot atm. I have the "bloodAuraEffects" set to true in the config.
- The Blood Flask doesn't grant additional blood capacity, nor does it give you extra blood upon slaying a mob like it should. It only gives you a bonus effect multiplier.

Seems to be working on version 0.1.4, but breaks on anything above that. Sadly using anything below 0.1.5 completely breaks the praetor scythe, so hopefully this can get fixed soon

**Comment by cojalexandru** [comment]
There are known issues with the "Blood Aura" system (being one of the first intricate things I've ever modded it turned out pretty bad). Still, because Eidolon doesn't seem to be getting any updates soon it would seem useless for me to keep working on an addon for it.

Sanguine Arsenal might return in the future as its own magic mod when I get the time to work on it, for now, it will be deprecated, no more updates are coming.
